= Use Flow Designer to Configure Google Sheets Connector 1.0.0 - Mule 4
:page-aliases: connectors::google/google-sheets-design-center.adoc, connectors::google/google-sheets-connector-design-center.adoc

Anypoint Design Center's Flow Designer enables you to create apps visually. To use Flow Designer, work with your Anypoint Platform administrator to ensure that you have a xref:access-management::environments.adoc#to-create-a-new-environment[Design environment]. For more information, see the xref:design-center::fd-tour.adoc[Flow Designer Tour].

To create an app in Flow Designer:

* Configure the trigger (source) for your app.
* Configure the target component for your app.

For information about connector field values, see
the xref:google-sheets-reference.adoc[Google Sheets Connector Reference].

== Configure the Input Source Trigger

A trigger starts your app. You can use the HTTP Listener operation to start your app from a browser or the `Scheduler` to start your app on a timed schedule. Anypoint Connector for SNS (Amazon SNS Connector) does not provide trigger operations.

. In Design Center, click *Create*.
. Click *Create new application* to open Flow Designer.
. Specify a value for *Project name*, and click *Create*.
. Click *Go straight to canvas* to exit *Let's get started*.
. Click on the trigger card.
. If you are using the HTTP Listener operation as a trigger, search for and select *HTTP Listener*.
. In the HTTP Listener's *General* tab, enter the path-absolute-URL that defines the resource location.
. Click off the trigger card.

Design Center automatically saves all changes.

== Configure the Target Component

The target component enables your app to process data received from the trigger. Google Sheets Connector provides operations that you can insert or update rows in a spreadsheets or get metadata information about spreadsheets.

To configure the target component:

. In the *Object Type* field, select the Google sheets object type.
. Click outside of the dialog.
. Click *+* next to the trigger card.
. In *Select a component*, search for `google` and select *Google Sheets Connector*.
. Select an operation.
. Click *Edit*.
. Click *Add Connection*.
. In the *Connection Name* field, select the configured connection.
. Complete the required fields.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
