= Use Flow Designer to Configure Google Sheets Connector 1.0.0 - Mule 4
:page-aliases: connectors::google/google-sheets-design-center.adoc, connectors::google/google-sheets-connector-design-center.adoc

Anypoint Design Center's Flow Designer enables you to create apps visually. To use Flow Designer, work with your Anypoint Platform administrator to ensure that you have a xref:access-management::environments.adoc#to-create-a-new-environment[Design environment]. For more information, see the xref:design-center::fd-tour.adoc[Flow Designer Tour].

To create an app in Flow Designer:

* Configure the trigger (source) for your app.
* Configure the target component for your app.

For information about connector field values, see
the xref:google-sheets-reference.adoc[Google Sheets Connector Reference].

== Configure the Trigger

Google Sheets Connector provides the *On New Row*, *On New Or Updated Row* and *On New Spreadsheet* triggers, which starts your app when a row is inserted, updated or new spreadsheet is created respectively. Alternatively, you can use:

* *HTTP Listener* to start your app from a browser
or with a command such as `curl`.
* *Scheduler* to start your app on a timed schedule

To configure the trigger:

. In Design Center, click *Create new*.
. Click *Create new application*.
. Specify a value for *Project name*, and click *Create*.
. Click *Go straight to canvas* to exit from *Let's get started*.
. In the middle of the canvas, click the empty trigger card to expand it.
. Configure the trigger for the connector.
+
To use the *On New Row* trigger, enter `google` in the search field and select *Google Sheets Connector*.
. Click *Add Connection*.
. Complete the required fields.
. Click *Test* to test the connection.
. Click *Save*.

== Configure the Target Component

The target component enables your app to process data received from the trigger. Google Sheets Connector provides operations that you can insert or update rows in a spreadsheets or get metadata information about spreadsheets.

To configure the target component:

. In the *Object Type* field, select the Google sheets object type.
. Click outside of the dialog.
. Click *+* next to the trigger card.
. In *Select a component*, search for `google` and select *Google Sheets Connector*.
. Select an operation.
. Click *Edit*.
. Click *Add Connection*.
. In the *Connection Name* field, select the configured connection.
. Complete the required fields.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
* https://help.mulesoft.com[MuleSoft Help Center]
