= Use Studio to Configure Google Sheets Connector 1.0.0 - Mule 4
:page-aliases: connectors::google/google-sheets-studio.adoc, connectors::google/google-sheets-connector-studio.adoc

Anypoint Studio (Studio) editors help you design and update your Mule applications, properties, and configuration files.

To add and configure a connector in Studio:

. Create a Mule project.
. Add the connector to your Mule project.
. Configure a source for the connector's flow.
. Add a connector operation to the flow.
. Configure a global element for the connector.

When you run the connector, you can view the app log to check for problems, as described in <<view-app-log,View the App Log>>.

If you are new to configuring connectors in Studio, see xref:connectors::introduction/intro-config-use-studio.adoc[Use Studio to Configure a Connector]. If, after reading this topic, you need additional information about the connector fields, see the xref:google-sheets-reference.adoc[Google Sheets Connector Reference].

[[create-mule-project]]
== Create a Mule Project

In Studio, create a new Mule project in which to add and configure the connector:

. In Studio, select *File > New > Mule Project*.
. Enter a name for your Mule project and click *Finish*.

[[add-connector-to-project]]
== Add the Connector to Your Mule Project

Add Google Sheets Connector to your Mule project to automatically populate the XML code with the connector's namespace and schema location and to add the required dependencies to the project's `pom.xml` file:

. In the *Mule Palette* view, click *(X) Search in Exchange*.
. In *Add Dependencies to Project*, type `google` in the search field.
. Click *Google Sheets Connector* in *Available modules*.
. Click *Add*.
. Click *Finish*.

Adding a connector to a Mule project in Studio does not make that connector available to other projects in your Studio workspace.

[[configure-input-source]]
== Configure a Source

A source (listener) initiates a flow when a specified condition is met.

You can configure one of these sources to use with Google Sheets Connector:

* *On New Row Listener* +
Start your app when the row is added into a spreadsheet.
* *On New or Updated Row Listener* +
Start your app when the row is added into or updated in a spreadsheet.
* *On New Spreadsheet Listener* +
Start your app when the new spreadsheet is created on your Google Drive.
* *HTTP Listener* +
Initiates a flow each time it receives a request on the configured host and port
* *Scheduler* +
Initiates a flow when a time-based condition is met

To configure the *On New Row Listener* source:

. In the *Mule Palette* view, select *Google Sheets > On New Row Listener*.
. Drag *On New Row Listener* source to the Studio canvas.
. On the *On New Row Listener* configuration screen, optionally change the value of the *Display Name* field.
. Enter the required information for the following fields:
+
[%header,cols="30s,70a"]
|===
|Studio Field |Description
|Connector configuration |Global Element Properties configuration name
|Scheduling Strategy a|Tells the source how it can poll the data. This field accepts two options:

* *Fixed Frequency* +
Polls for data at a specified number of milliseconds, seconds, minutes, hours, or days. The default is 1000 milliseconds.
* *Cron* +
Accepts an expression that polls for data based on a filter, such as every Monday in a month at a given time. See xref:mule-runtime::scheduler-concept.adoc#cron-expressions[Cron Expressions] for examples.
|Spreadsheet ID|Id of the spreadsheet to check for a new row in
|Worksheet Name|Name of the sheet to check for a new row in
|===
+
. Click the plus sign (*+*) next to the *Connector configuration* field to <<configure-global-element,configure a global element>> that can be used by all instances of the *On New Row Listener* listener in the app.


[[add-connector-operation]]
== Add a Connector Operation to the Flow

When you add a connector operation to your flow, you immediately define a specific operation for that connector to perform.

To add an operation for Google Sheets Connector, follow these steps:

. In the *Mule Palette* view, select *Google Sheets* and then select the desired operation.
. Drag the operation onto the Studio canvas to the right of the source.

Each Google Sheets operation has its own required fields in Anypoint Studio. For more information, see
the xref:google-sheets-reference.adoc[Google Sheets Reference].

[[configure-global-element]]
== Configure a Global Element

When you configure a connector, it’s best to configure a global element that all instances of that connector in the app can use. Configuring a global element requires you to provide the authentication credentials that the connector requires to access the target Google system. Google Sheets Connector supports OAuth 2.0 authentication.

To configure the global element for Google Sheets Connector, follow these steps:

. Select the operation in the Studio canvas.
. In the configuration screen for the operation, click the plus sign (*+*) next to the *Connector configuration* field to access the global element configuration fields.
. On the *General* tab, configure the authentication for the connection as described in the <<oauth-authentication,OAuth 2.0 Authentication>> section.
+
You can reference a configuration file that contains ANT-style property placeholders (recommended), or you can enter your authorization credentials in the global configuration properties. For information about the benefits of using property placeholders and how to configure them, see xref:connectors::introduction/intro-connector-configuration-overview.adoc[Anypoint Connector Configuration].
+
. On the *Advanced* tab, optionally specify reconnection information, including a reconnection strategy.
. Click *Test Connection* to confirm that Mule can connect with the specified server. +
. Click *OK*.

[[oauth-authentication]]
=== OAuth 2.0 Authentication

Enter the following information on the *General* tab of the *Global Element Properties* screen to configure OAuth 2.0 Authentication:

[%header,cols="30s,70a"]
|===
|Field |Description
|Consumer key |Enter a consumer key belonging to your authentification server's client application.
|Consumer password |Enter a consumer password belonging to your authentification server's client application.
|Authorization url |URL for the oauth authorization, filled in by the connector.
|Access token url |URL for the acces token, filled in by the connector.
|Scopes |Scopes used by the connector.
|Callback path |Callback path used during oauth dance.
|Authorize path |Authorize path used during oauth dance. This path is used to start the authorization process (oauth dance)
|Object store |Defines object store, which will contains access token gained during the authorization.
|===

[[configure-other-fields]]
== Configure Additional Connector Fields

After you configure a global element for Workday Connector, configure the the other required fields for the connector, as described in xref:google-sheets-reference.adoc[Google Sheets Connector Reference].

[[view-app-log]]
== View the App Log

To check for problems, you can view the app log as follows:

* If you’re running the app from Anypoint Platform, the output is visible in the Anypoint Studio console window.
* If you’re running the app using Mule from the command line, the app log is visible in your OS console.

Unless the log file path is customized in the app’s log file (`log4j2.xml`), you can also view the app log in the default location `MULE_HOME/logs/<app-name>.log`.

== Next Step

After configuring Google Sheets Connector in Studio, see the xref:google-sheets-connector-examples.adoc[Examples] to demonstrate how to use this connector.

== See Also

* xref:connectors::introduction/introduction-to-anypoint-connectors.adoc[Introduction to Anypoint Connectors]
xref:connectors::introduction/intro-config-use-studio.adoc[Use Studio to Configure a Connector]
* https://help.mulesoft.com[MuleSoft Help Center]
